### ISSUE TITLE
what's the different pinchstart | pinchend & pinchin | pinchout

### ISSUE THREAD

**Issue by boomyao** [react-component/gesture#1]
so many callback function that i don't know which one should i do ???

**Comment by paranoidjk** [comment]
The api is basicly as same as [hammer.js](http://hammerjs.github.io/recognizer-pinch/).

They are in diffrent point of view.

1. `pinchstart / pinchmove / pinchend / pinchcancel` is based on TouchEvent view, they are the low level api.

2. `pinch` in a uniform api, or a alias，both `pinchstart / pinchmove / pinchend / pinchcancel` will trigger `pinch` at the same time. It's just for convenient.

3. `pinchin`, `pinchout` is the top level api, which calculated the actually gesture behavior for users. `pinchin` means zoom out， `pinchout` means zoom in.
